### ISSUE TITLE
Path sent to Graphite should include Node version

### ISSUE THREAD

**Issue by leebow** [happner/test-metrics#1]
The current path structure is for example:
```
repo.happner-2.results.0-endpoint-service.requires and initializes the endpoint service, config with no endpoints
```
This should be modified to:
```
# eg: node 0.1.0
repo.happner-2.results.node_version_0.0-endpoint-service.requires and initializes the endpoint service, config with no endpoints
# eg: node 7
repo.happner-2.results.node_version_7.0-endpoint-service.requires and initializes the endpoint service, config with no endpoints
```
...where only the MAJOR version is included in the path.

**Comment by leebow** [comment]
@nomilous, @southbite please confirm the above path structure is correct - thanks

**Comment by nomilous** [comment]
We might want to only use the major version of node. Would result in graphite tree:

/node_0
/node_4
/node_5
/node_6

etc

If we also include the minor version then our graphs would move onto a new tree with every minor release.

**Comment by leebow** [comment]
Good point - thanks @nomilous

**Comment by nomilous** [comment]
Im worried that their may be nothing handling recursive suites (contexts).

eg:

```javascript
describe('outer', function () {
  context('inner', function () {
    it('test', function () {
      //
    });
  }
});
```

here is an example with no inner suite: https://github.com/happner/test-metrics/blob/master/test/fixtures/tracey-sample.json#L227

here is an example with inner suite: https://github.com/happner/test-metrics/blob/master/test/fixtures/tracey-sample.json#L397

it needs to recurse the suites to produce
`repo.project.results.node_version.suite_name[.recursed_nested_suitename].test_name`

or flatten the nested suite names into `.outer/inner/deeper.` as one key but still reflecting the full path

**Comment by leebow** [comment]
I think this has already been taken care of - I will confirm.

UPDATE: confirmed that this is being taken care of - extra tests added
